// apps/angular-ssr/src/app/pages/users/users.component.ts
import { Component, OnInit, signal, inject, PLATFORM_ID } from '@angular/core';
import { CommonModule, DOCUMENT, isPlatformBrowser } from '@angular/common';
import { RouterLink } from '@angular/router';
import { Title, Meta } from '@angular/platform-browser';
import { getUsers } from '@ssr-comparison/api';
import type { User } from '@ssr-comparison/types';

@Component({
  selector: 'app-users',
  standalone: true,
  imports: [CommonModule, RouterLink],
  template: `
    <div class="container mx-auto px-4 py-12">
      <nav aria-label="Breadcrumb" class="mb-8">
        <ol class="flex items-center space-x-2 text-sm text-muted-foreground">
          <li><a routerLink="/" class="hover:text-foreground">Home</a></li>
          <li>/</li>
          <li class="text-foreground">Users</li>
        </ol>
      </nav>

      <h1 class="mb-8 text-4xl font-bold">Users</h1>
      <p class="mb-8 text-muted-foreground">Total: {{ users().length }} users</p>

      <div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        @for (user of users(); track user.id) {
          <a
            [routerLink]="['/users', user.id]"
            class="group rounded-lg border bg-card p-6 transition-shadow hover:shadow-lg"
          >
            <h2 class="mb-2 text-xl font-semibold group-hover:text-primary">
              {{ user.name }}
            </h2>
            <p class="text-sm text-muted-foreground">@{{ user.username }}</p>
            <p class="mt-2 text-sm text-muted-foreground">{{ user.email }}</p>
            <p class="mt-4 text-xs text-muted-foreground">{{ user.company.name }}</p>
          </a>
        }
      </div>
    </div>
  `,
})
export class UsersComponent implements OnInit {
  private title = inject(Title, { optional: true });
  private meta = inject(Meta, { optional: true });
  private document = inject(DOCUMENT, { optional: true });
  private platformId = inject(PLATFORM_ID);
  
  users = signal<User[]>([]);

  async ngOnInit() {
    const usersData = await getUsers();
    this.users.set(usersData);

    // Set meta tags
    if (this.title) {
      this.title.setTitle('Users - SSR Comparison Suite');
    }
    if (this.meta) {
      this.meta.updateTag({
        name: 'description',
        content: 'Browse all users from JSONPlaceholder API',
      });
      this.meta.updateTag({
        property: 'og:title',
        content: 'Users - SSR Comparison Suite',
      });
      this.meta.updateTag({
        property: 'og:description',
        content: 'Browse all users from JSONPlaceholder API',
      });
      this.meta.updateTag({
        property: 'og:type',
        content: 'website',
      });
    }
    
    // Add canonical link and JSON-LD only if document is available
    if (isPlatformBrowser(this.platformId) && this.document) {
      const origin = window.location.origin;
      const existingCanonical = this.document.querySelector('link[rel="canonical"]');
      if (existingCanonical) existingCanonical.remove();
      const link = this.document.createElement('link');
      link.setAttribute('rel', 'canonical');
      link.setAttribute('href', `${origin}/users`);
      this.document.head.appendChild(link);

      // Add JSON-LD structured data
      const breadcrumbs = {
        '@context': 'https://schema.org',
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: `${origin}/` },
          { '@type': 'ListItem', position: 2, name: 'Users', item: `${origin}/users` },
        ],
      };
      const script = this.document.createElement('script');
      script.type = 'application/ld+json';
      script.text = JSON.stringify(breadcrumbs);
      this.document.head.appendChild(script);
    }
  }
}

// apps/nuxt-ssr/pages/users/index.vue
<template>
  <div class="container mx-auto px-4 py-12">
    <nav aria-label="Breadcrumb" class="mb-8">
      <ol class="flex items-center space-x-2 text-sm text-muted-foreground">
        <li><NuxtLink to="/" class="hover:text-foreground">Home</NuxtLink></li>
        <li>/</li>
        <li class="text-foreground">Users</li>
      </ol>
    </nav>

    <h1 class="mb-8 text-4xl font-bold">Users</h1>
    <p class="mb-8 text-muted-foreground">Total: {{ users.length }} users</p>

    <div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
      <NuxtLink
        v-for="user in users"
        :key="user.id"
        :to="`/users/${user.id}`"
        :class="cardClass({ variant: 'default' })"
      >
        <h2 class="mb-2 text-xl font-semibold group-hover:text-primary">
          {{ user.name }}
        </h2>
        <p class="text-sm text-muted-foreground">@{{ user.username }}</p>
        <p class="mt-2 text-sm text-muted-foreground">{{ user.email }}</p>
        <p class="mt-4 text-xs text-muted-foreground">{{ user.company.name }}</p>
      </NuxtLink>
    </div>
  </div>
</template>

<script setup lang="ts">
import { getUsers } from '@ssr-comparison/api';
import { cardClass } from '@ssr-comparison/ui';

const origin = useSiteOrigin();
const canonical = computed(() => `${origin.value}/users`);
const breadcrumbsJsonLd = computed(() =>
  JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: `${origin.value}/` },
      { '@type': 'ListItem', position: 2, name: 'Users', item: `${origin.value}/users` },
    ],
  })
);

const users = await getUsers();

useHead({
  title: 'Users - SSR Comparison Suite',
  meta: [
    {
      name: 'description',
      content: 'Browse all users from JSONPlaceholder API',
    },
    {
      property: 'og:title',
      content: 'Users - SSR Comparison Suite',
    },
    {
      property: 'og:description',
      content: 'Browse all users from JSONPlaceholder API',
    },
    {
      property: 'og:type',
      content: 'website',
    },
  ],
  link: [
    {
      rel: 'canonical',
      href: canonical,
    },
  ],
  script: [
    {
      type: 'application/ld+json',
      children: breadcrumbsJsonLd,
    },
  ],
});
</script>
