// apps/nuxt-ssr/pages/albums/index.vue
<template>
  <div class="container mx-auto px-4 py-12">
    <nav aria-label="Breadcrumb" class="mb-8">
      <ol class="flex items-center space-x-2 text-sm text-muted-foreground">
        <li><NuxtLink to="/" class="hover:text-foreground">Home</NuxtLink></li>
        <li>/</li>
        <li class="text-foreground">Albums</li>
      </ol>
    </nav>

    <h1 class="mb-8 text-4xl font-bold">Albums</h1>
    <p class="mb-8 text-muted-foreground">Total: {{ albums.length }} albums</p>

    <div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
      <NuxtLink
        v-for="album in albums"
        :key="album.id"
        :to="`/albums/${album.id}`"
        :class="cardClass({ variant: 'default' })"
      >
        <h2 class="mb-2 text-xl font-semibold group-hover:text-primary">
          {{ album.title }}
        </h2>
        <div class="mt-4 text-xs text-muted-foreground">
          Album #{{ album.id }} • User {{ album.userId }}
        </div>
      </NuxtLink>
    </div>
  </div>
</template>

<script setup lang="ts">
import { getAlbums } from '@ssr-comparison/api';
import { cardClass } from '@ssr-comparison/ui';

const origin = useSiteOrigin();
const canonical = computed(() => `${origin.value}/albums`);
const breadcrumbsJsonLd = computed(() =>
  JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: `${origin.value}/` },
      { '@type': 'ListItem', position: 2, name: 'Albums', item: `${origin.value}/albums` },
    ],
  })
);

const albums = await getAlbums();

useHead({
  title: 'Albums - SSR Comparison Suite',
  meta: [
    {
      name: 'description',
      content: 'Browse all albums from JSONPlaceholder API',
    },
    {
      property: 'og:title',
      content: 'Albums - SSR Comparison Suite',
    },
    {
      property: 'og:description',
      content: 'Browse all albums from JSONPlaceholder API',
    },
    {
      property: 'og:type',
      content: 'website',
    },
  ],
  link: [
    {
      rel: 'canonical',
      href: canonical,
    },
  ],
  script: [
    {
      type: 'application/ld+json',
      children: breadcrumbsJsonLd,
    },
  ],
});
</script>

// apps/next-ssr/src/app/albums/page.tsx
import type { Metadata } from 'next';
import Link from 'next/link';
import { getAlbums } from '@ssr-comparison/api';
import { generateCanonicalUrl, generateBreadcrumbs } from '@ssr-comparison/utils';
import { getRequestOrigin } from '@/lib/seo';

export async function generateMetadata(): Promise<Metadata> {
  const origin = await getRequestOrigin();
  return {
    title: 'Albums - SSR Comparison Suite',
    description: 'Browse all albums from JSONPlaceholder API',
    openGraph: {
      title: 'Albums - SSR Comparison Suite',
      description: 'Browse all albums from JSONPlaceholder API',
      type: 'website',
    },
    alternates: {
      canonical: generateCanonicalUrl('/albums', origin),
    },
  };
}

export default async function AlbumsPage() {
  const origin = await getRequestOrigin();
  const albums = await getAlbums();

  const breadcrumbs = generateBreadcrumbs([
    { label: 'Home', href: `${origin}/` },
    { label: 'Albums', href: `${origin}/albums` },
  ]);

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbs) }}
      />
      <div className="container mx-auto px-4 py-12">
        <nav aria-label="Breadcrumb" className="mb-8">
          <ol className="flex items-center space-x-2 text-sm text-muted-foreground">
            <li>
              <Link href="/" className="hover:text-foreground">
                Home
              </Link>
            </li>
            <li>/</li>
            <li className="text-foreground">Albums</li>
          </ol>
        </nav>

        <h1 className="mb-8 text-4xl font-bold">Albums</h1>
        <p className="mb-8 text-muted-foreground">
          Total: {albums.length} albums
        </p>

        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {albums.map((album) => (
            <Link
              key={album.id}
              href={`/albums/${album.id}`}
              className="group rounded-lg border bg-card p-6 transition-shadow hover:shadow-lg"
            >
              <h2 className="mb-2 text-xl font-semibold group-hover:text-primary">
                {album.title}
              </h2>
              <div className="mt-4 text-xs text-muted-foreground">
                Album #{album.id} • User {album.userId}
              </div>
            </Link>
          ))}
        </div>
      </div>
    </>
  );
}
