// apps/next-ssr/src/app/posts/page.tsx
import type { Metadata } from 'next';
import Link from 'next/link';
import { getPosts } from '@ssr-comparison/api';
import { generateCanonicalUrl, DEFAULT_INFINITE_LIMIT, encodeCursor } from '@ssr-comparison/utils';
import { generateBreadcrumbs } from '@ssr-comparison/utils';
import { InfinitePosts } from '@/components/infinite-posts';
import { getRequestOrigin } from '@/lib/seo';

export async function generateMetadata(): Promise<Metadata> {
  const origin = await getRequestOrigin();
  return {
    title: 'Posts - SSR Comparison Suite',
    description: 'Browse all posts from JSONPlaceholder API',
    openGraph: {
      title: 'Posts - SSR Comparison Suite',
      description: 'Browse all posts from JSONPlaceholder API',
      type: 'website',
    },
    alternates: {
      canonical: generateCanonicalUrl('/posts', origin),
    },
  };
}

export default async function PostsPage() {
  const origin = await getRequestOrigin();

  const posts = await getPosts();
  const total = posts.length;
  const limit = DEFAULT_INFINITE_LIMIT;
  const totalPages = Math.ceil(total / limit);
  const data = posts.slice(0, limit);
  const nextCursor = 2 <= totalPages ? encodeCursor(2) : null;

  const initial = {
    data,
    total,
    page: 1,
    limit,
    totalPages,
    nextCursor,
  };

  const breadcrumbs = generateBreadcrumbs([
    { label: 'Home', href: `${origin}/` },
    { label: 'Posts', href: `${origin}/posts` },
  ]);

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbs) }}
      />
      <div className="container mx-auto px-4 py-12">
        <nav aria-label="Breadcrumb" className="mb-8">
          <ol className="flex items-center space-x-2 text-sm text-muted-foreground">
            <li>
              <Link href="/" className="hover:text-foreground">
                Home
              </Link>
            </li>
            <li>/</li>
            <li className="text-foreground">Posts</li>
          </ol>
        </nav>

        <h1 className="mb-8 text-4xl font-bold">Posts</h1>
        <p className="mb-8 text-muted-foreground">Total: {initial.total} posts</p>

        <InfinitePosts initial={initial} />
      </div>
    </>
  );
}

// apps/nuxt-ssr/pages/posts/index.vue
<template>
  <div class="container mx-auto px-4 py-12">
    <nav aria-label="Breadcrumb" class="mb-8">
      <ol class="flex items-center space-x-2 text-sm text-muted-foreground">
        <li><NuxtLink to="/" class="hover:text-foreground">Home</NuxtLink></li>
        <li>/</li>
        <li class="text-foreground">Posts</li>
      </ol>
    </nav>

    <h1 class="mb-8 text-4xl font-bold">Posts</h1>
    <p class="mb-8 text-muted-foreground">Total: {{ initial.total }} posts</p>

    <InfinitePosts :initial="initial" />
  </div>
</template>

<script setup lang="ts">
import { DEFAULT_INFINITE_LIMIT } from '@ssr-comparison/utils';

const origin = useSiteOrigin();
const canonical = computed(() => `${origin.value}/posts`);
const breadcrumbsJsonLd = computed(() =>
  JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: `${origin.value}/` },
      { '@type': 'ListItem', position: 2, name: 'Posts', item: `${origin.value}/posts` },
    ],
  })
);

const { data: initial } = await useAsyncData('posts:first', () =>
  $fetch('/api/posts', { query: { limit: DEFAULT_INFINITE_LIMIT } })
);

useHead({
  title: 'Posts - SSR Comparison Suite',
  meta: [
    {
      name: 'description',
      content: 'Browse all posts from JSONPlaceholder API',
    },
    {
      property: 'og:title',
      content: 'Posts - SSR Comparison Suite',
    },
    {
      property: 'og:description',
      content: 'Browse all posts from JSONPlaceholder API',
    },
    {
      property: 'og:type',
      content: 'website',
    },
  ],
  link: [
    {
      rel: 'canonical',
      href: canonical,
    },
  ],
  script: [
    {
      type: 'application/ld+json',
      children: breadcrumbsJsonLd,
    },
  ],
});
</script>
